%DefinicionDePlantas
planta('Abrojo').
planta('Acacia').
planta('Acanto').
planta('Acedera').
planta('Aceite de oliva').
planta('Aceitilla').
planta('Acelga').
planta('Achicoria').
planta('Aconito').
planta('Agar-agar').
planta('Aguacate').
planta('Ajenjo').
planta('Ajo').
planta('Albahaca').
planta('Alcachofa').
planta('Alcanfor').
planta('Alfalfa').
planta('Alholva').
planta('Alpiste').
planta('Anacahuite').
planta('Anagalida').
planta('Anis estrella').
planta('Anis').
planta('Apio').
planta('Arnica').
planta('Arroz').
planta('Artemisa').
planta('Avena').
planta('Azafran').
planta('Azahar').
planta('Beleño').
planta('Belladona').
planta('Benjui').
planta('Berro').
planta('Betonia').
planta('Boldo').
planta('Borraja').
planta('Brionia').
planta('Cabellos de elote').
planta('Calendula').
planta('Canela').
planta('Capulin').
planta('Cardo santo').
planta('Cardo').
planta('Cascara sagrada').
planta('Castaño de indias').
planta('Cebada').
planta('Cebolla').
planta('Cedron').
planta('Cerezo').
planta('Chaparro amargoso').
planta('Chia').
planta('Chicalote').
planta('Cilantro').
planta('Cipres').
planta('Ciruela').
planta('Clavo').
planta('Cola de caballo').
planta('Colchico').
planta('Coquito de aceite').
planta('Crataegus').
planta('Cuachalalate').
planta('Cuasia').
planta('Cuercillo').
planta('Damiana').
planta('Diente de leon').
planta('Digital').
planta('Doradilla').
planta('Encina').
planta('Encino rojo').
planta('Enebro').
planta('Epazote').
planta('Esparrago').
planta('Espinacas').
planta('Espino').
planta('Espinosilla').
planta('Estafiate').
planta('Eucalipto').
planta('Fenogreco').
planta('Fresno').
planta('Gelsemio').
planta('Genciana').
planta('Geranio').
planta('Germen de trigo').
planta('Girasol').
planta('Gobernadora').
planta('Gordolobo').
planta('Grama').
planta('Granada').
planta('Guayaba').
planta('Hamamelis').
planta('Helecho macho').
planta('Helecho').
planta('Hiedra').
planta('Hierba del pollo').
planta('Hierbabuena').
planta('Higuera').
planta('Hinojo').
planta('Hisopol').
planta('Ipecacuana').
planta('Jengibre').
planta('Jugo de limon').
planta('Jugo de toronja').
planta('Jugo de vastago de platano morado').
planta('Laurel').
planta('Lavanda').
planta('Leche de higuera').
planta('Lechuga').
planta('Limon').
planta('Linaza').
planta('Lino').
planta('Llanten').
planta('Lupulo').
planta('Malva').
planta('Malvavisco').
planta('Manzanilla').
planta('Marrubio').
planta('Mastuerzo').
planta('Matarique').
planta('Mate').
planta('Melisa').
planta('Membrillo').
planta('Menta').
planta('Mezquite').
planta('Miel').
planta('Milenrama').
planta('Monacillo').
planta('Mostaza').
planta('Muerdago').
planta('Muicle').
planta('Naranja').
planta('Nogal').
planta('Nuez de kola').
planta('Nuez vomica').
planta('Ocote').
planta('Oregano').
planta('Ortiga').
planta('Papaloquelite').
planta('Papaya').
planta('Pasiflora').
planta('Perejil').
planta('Pimiento').
planta('Pingüica').
planta('Pino').
planta('Pirul').
planta('Prodigiosa').
planta('Puerro').
planta('Quina amarilla').
planta('Quina roja').
planta('Quina').
planta('Rabano').
planta('Retama').
planta('Ricino').
planta('Roble').
planta('Romero').
planta('Rosal').
planta('Ruda').
planta('Ruibarbo').
planta('Sabina').
planta('Salvia').
planta('Sanguinaria').
planta('Sauco').
planta('Semilla de calabaza').
planta('Siempreviva').
planta('Simonillo').
planta('Tabachin').
planta('Tabaco').
planta('Tabaquillo').
planta('Tamarindo').
planta('Te de limon').
planta('Te negro').
planta('Tecomasuchil').
planta('Tejocote').
planta('Tila').
planta('Tlachichinole').
planta('Toloache').
planta('Tomillo').
planta('Toronja').
planta('Toronjil').
planta('Tronadora').
planta('Uva').
planta('Valeriana').
planta('Verbena').
planta('Violeta').
planta('Yohimbe').
planta('Zanahoria').
planta('Zarzamora').
planta('Zarzaparrilla').
planta('Zoapatle').


unirPlantaImagen('Malva','C:/Proyecto/yerberito/Malva.jpg').
unirPlantaImagen('Zarzaparrilla','C:/Proyecto/yerberito/Zarzaparrilla.jpg').
unirPlantaImagen('Anis','C:/Proyecto/yerberito/Anis.jpg').
unirPlantaImagen('Perejil','C:/Proyecto/yerberito/Perejil.jpg').
unirPlantaImagen('Sanguinaria','C:/Proyecto/yerberito/Sanguinaria.jpg').
unirPlantaImagen('Limon','C:/Proyecto/yerberito/Limon.jpg').
unirPlantaImagen('Sauco','C:/Proyecto/yerberito/Sauco.jpg').
unirPlantaImagen('Arnica','C:/Proyecto/yerberito/Arnica.jpg').
unirPlantaImagen('Llanten','C:/Proyecto/yerberito/Llanten.jpg').
unirPlantaImagen('Fenogreco','C:/Proyecto/yerberito/Fenogreco.jpg').
unirPlantaImagen('Zarzamora','C:/Proyecto/yerberito/Zarzamora.jpg').
unirPlantaImagen('Salvia','C:/Proyecto/yerberito/Salvia.jpg').
unirPlantaImagen('Tilo','C:/Proyecto/yerberito/Tilo.jpg').
unirPlantaImagen('Valeriana','C:/Proyecto/yerberito/Valeriana.jpg').
unirPlantaImagen('Yerbabuena','C:/Proyecto/yerberito/Yerbabuena.jpg').
unirPlantaImagen('Manzanilla','C:/Proyecto/yerberito/Manzanilla.jpg').
unirPlantaImagen('Jugo_de_limon','C:/Proyecto/yerberito/Jugo_de_limon.jpg').
unirPlantaImagen('Jugo_de_toronja','C:/Proyecto/yerberito/Jugo_de_toronja.jpg').
unirPlantaImagen('Pinguica','C:/Proyecto/yerberito/Pinguica.jpg').
unirPlantaImagen('Quinoa_roja','C:/Proyecto/yerberito/Quinoa_roja.jpg').
unirPlantaImagen('Encino_rojo','C:/Proyecto/yerberito/Encino_rojo.jpg').
unirPlantaImagen('Pimiento','C:/Proyecto/yerberito/Pimiento.jpg').
unirPlantaImagen('Huramelis','C:/Proyecto/yerberito/Huramelis.jpg').
unirPlantaImagen('Cola_de_caballo','C:/Proyecto/yerberito/Cola_de_caballo.jpg').
unirPlantaImagen('Arnica','C:/Proyecto/yerberito/Arnica.jpg').
unirPlantaImagen('Ajenjo','C:/Proyecto/yerberito/Ajenjo.jpg').
unirPlantaImagen('Germen_de_trigo','C:/Proyecto/yerberito/Germen_de_trigo.jpg').
unirPlantaImagen('Quira','C:/Proyecto/yerberito/Quira.jpg').
unirPlantaImagen('Canela','C:/Proyecto/yerberito/Canela.jpg').
unirPlantaImagen('Alholva','C:/Proyecto/yerberito/Alholva.jpg').
unirPlantaImagen('Eucalipto','C:/Proyecto/yerberito/Eucalipto.jpg').
unirPlantaImagen('Cebada','C:/Proyecto/yerberito/Cebada.jpg').
unirPlantaImagen('Tabachin','C:/Proyecto/yerberito/Tabachin.jpg').
unirPlantaImagen('Borraja','C:/Proyecto/yerberito/Borraja.jpg').
unirPlantaImagen('Gerciana','C:/Proyecto/yerberito/Gerciana.jpg').
unirPlantaImagen('Limon','C:/Proyecto/yerberito/Limon.jpg').
unirPlantaImagen('Genciana','C:/Proyecto/yerberito/Genciana.jpg').
unirPlantaImagen('Cardo','C:/Proyecto/yerberito/Cardo.jpg').
unirPlantaImagen('Chicalote','C:/Proyecto/yerberito/Chicalote.jpg').
unirPlantaImagen('Alcanfor','C:/Proyecto/yerberito/Alcanfor.jpg').
unirPlantaImagen('Toronja','C:/Proyecto/yerberito/Toronja.jpg').
unirPlantaImagen('Merrubio','C:/Proyecto/yerberito/Merrubio.jpg').
unirPlantaImagen('Toloache','C:/Proyecto/yerberito/Toloache.jpg').
unirPlantaImagen('Oregano','C:/Proyecto/yerberito/Oregano.jpg').
unirPlantaImagen('Lupulo','C:/Proyecto/yerberito/Lupulo.jpg').
unirPlantaImagen('Cuasia','C:/Proyecto/yerberito/Cuasia.jpg').
unirPlantaImagen('Uva','C:/Proyecto/yerberito/Uva.jpg').
unirPlantaImagen('Cerezo','C:/Proyecto/yerberito/Cerezo.jpg').
unirPlantaImagen('Rosal','C:/Proyecto/yerberito/Rosal.jpg').
unirPlantaImagen('Encina','C:/Proyecto/yerberito/Encina.jpg').
unirPlantaImagen('Borraga','C:/Proyecto/yerberito/Borraga.jpg').
unirPlantaImagen('Anacahuite','C:/Proyecto/yerberito/Anacahuite.jpg').
unirPlantaImagen('Benjui','C:/Proyecto/yerberito/Benjui.jpg').
unirPlantaImagen('Rabano','C:/Proyecto/yerberito/Rabano.jpg').
unirPlantaImagen('Ipecacuana','C:/Proyecto/yerberito/Ipecacuana.jpg').
unirPlantaImagen('Mostaza','C:/Proyecto/yerberito/Mostaza.jpg').
unirPlantaImagen('Ortiga','C:/Proyecto/yerberito/Ortiga.jpg').
unirPlantaImagen('Espinosilla','C:/Proyecto/yerberito/Espinosilla.jpg').
unirPlantaImagen('Romero','C:/Proyecto/yerberito/Romero.jpg').
unirPlantaImagen('Diente_de_leon','C:/Proyecto/yerberito/Diente_de_leon.jpg').
unirPlantaImagen('Aceite_de_oliva','C:/Proyecto/yerberito/Aceite_de_oliva.jpg').
unirPlantaImagen('Retama','C:/Proyecto/yerberito/Retama.jpg').
unirPlantaImagen('Cabellos_de_elote','C:/Proyecto/yerberito/Cabellos_de_elote.jpg').
unirPlantaImagen('Pinguica','C:/Proyecto/yerberito/Pinguica.jpg').
unirPlantaImagen('Ajo','C:/Proyecto/yerberito/Ajo.jpg').
unirPlantaImagen('Cebolla','C:/Proyecto/yerberito/Cebolla.jpg').
unirPlantaImagen('Hiedra','C:/Proyecto/yerberito/Hiedra.jpg').
unirPlantaImagen('Cuachalalate','C:/Proyecto/yerberito/Cuachalalate.jpg').
unirPlantaImagen('Siempreviva','C:/Proyecto/yerberito/Siempreviva.jpg').
unirPlantaImagen('Mastuerzo','C:/Proyecto/yerberito/Mastuerzo.jpg').
unirPlantaImagen('Higuera','C:/Proyecto/yerberito/Higuera.jpg').
unirPlantaImagen('Toronjil','C:/Proyecto/yerberito/Toronjil.jpg').
unirPlantaImagen('Boldo','C:/Proyecto/yerberito/Boldo.jpg').
unirPlantaImagen('Linaza','C:/Proyecto/yerberito/Linaza.jpg').
unirPlantaImagen('Laurel','C:/Proyecto/yerberito/Laurel.jpg').
unirPlantaImagen('Briania','C:/Proyecto/yerberito/Briania.jpg').
unirPlantaImagen('Nuez_de_kcla','C:/Proyecto/yerberito/Nuez_de_kcla.jpg').
unirPlantaImagen('Tejocote','C:/Proyecto/yerberito/Tejocote.jpg').
unirPlantaImagen('Achicoria','C:/Proyecto/yerberito/Achicoria.jpg').
unirPlantaImagen('Apio','C:/Proyecto/yerberito/Apio.jpg').
unirPlantaImagen('Sanguinaria','C:/Proyecto/yerberito/Sanguinaria.jpg').
unirPlantaImagen('Berro','C:/Proyecto/yerberito/Berro.jpg').
unirPlantaImagen('Matarique','C:/Proyecto/yerberito/Matarique.jpg').
unirPlantaImagen('Tronadora','C:/Proyecto/yerberito/Tronadora.jpg').
unirPlantaImagen('Bucalipto','C:/Proyecto/yerberito/Bucalipto.jpg').
unirPlantaImagen('Damiana','C:/Proyecto/yerberito/Damiana.jpg').
unirPlantaImagen('Capulin','C:/Proyecto/yerberito/Capulin.jpg').
unirPlantaImagen('Mezquite','C:/Proyecto/yerberito/Mezquite.jpg').
unirPlantaImagen('Tlalchichinole','C:/Proyecto/yerberito/Tlalchichinole.jpg').
unirPlantaImagen('Membrillo','C:/Proyecto/yerberito/Membrillo.jpg').
unirPlantaImagen('Arroz','C:/Proyecto/yerberito/Arroz.jpg').
unirPlantaImagen('Guayaba','C:/Proyecto/yerberito/Guayaba.jpg').
unirPlantaImagen('Albahaca','C:/Proyecto/yerberito/Albahaca.jpg').
unirPlantaImagen('Granada','C:/Proyecto/yerberito/Granada.jpg').
unirPlantaImagen('Sinionillo','C:/Proyecto/yerberito/Sinionillo.jpg').
unirPlantaImagen('Chaparro_amargoso','C:/Proyecto/yerberito/Chaparro_amargoso.jpg').
unirPlantaImagen('Muicle','C:/Proyecto/yerberito/Muicle.jpg').
unirPlantaImagen('Monacillo','C:/Proyecto/yerberito/Monacillo.jpg').
unirPlantaImagen('Naranja','C:/Proyecto/yerberito/Naranja.jpg').
unirPlantaImagen('Tamarindo','C:/Proyecto/yerberito/Tamarindo.jpg').
unirPlantaImagen('Quina','C:/Proyecto/yerberito/Quina.jpg').
unirPlantaImagen('Tabequillo','C:/Proyecto/yerberito/Tabequillo.jpg').
unirPlantaImagen('Ruibaxbo','C:/Proyecto/yerberito/Ruibaxbo.jpg').
unirPlantaImagen('Anis_estrella','C:/Proyecto/yerberito/Anis_estrella.jpg').
unirPlantaImagen('Ipecacuana','C:/Proyecto/yerberito/Ipecacuana.jpg').
unirPlantaImagen('Cedron','C:/Proyecto/yerberito/Cedron.jpg').
unirPlantaImagen('Te_de_limon','C:/Proyecto/yerberito/Te_de_limon.jpg').
unirPlantaImagen('Genciana','C:/Proyecto/yerberito/Genciana.jpg').
unirPlantaImagen('Grama','C:/Proyecto/yerberito/Grama.jpg').
unirPlantaImagen('Granado','C:/Proyecto/yerberito/Granado.jpg').
unirPlantaImagen('Gordolobo','C:/Proyecto/yerberito/Gordolobo.jpg').

%PlantasDeLasQueSeObtieneMedicamento
unirPlantaImagen('Digital','C:/Proyecto/yerberito/Digital.jpg').
unirPlantaImagen('Opio','C:/Proyecto/yerberito/Opio.jpg').
unirPlantaImagen('Ipeca','C:/Proyecto/yerberito/Ipeca.jpg').
unirPlantaImagen('Nuez_vomica','C:/Proyecto/yerberito/Nuez_vomica.jpg').
unirPlantaImagen('Eleboro_blanco','C:/Proyecto/yerberito/Eleboro_blanco.jpg').
unirPlantaImagen('Colchico','C:/Proyecto/yerberito/Colchico.jpg').
unirPlantaImagen('Belladona','C:/Proyecto/yerberito/Belladona.jpg').
unirPlantaImagen('Quina','C:/Proyecto/yerberito/Quina.jpg').
unirPlantaImagen('Cacao','C:/Proyecto/yerberito/Cacao.jpg').
unirPlantaImagen('Retama','C:/Proyecto/yerberito/Retama.jpg').
unirPlantaImagen('Coca','C:/Proyecto/yerberito/Coca.jpg').
unirPlantaImagen('Peyote','C:/Proyecto/yerberito/Peyote.jpg').
unirPlantaImagen('Efedra','C:/Proyecto/yerberito/Efedra.jpg').
unirPlantaImagen('Barrasco','C:/Proyecto/yerberito/Barrasco.jpg').
unirPlantaImagen('Nenufar_amarillo','C:/Proyecto/yerberito/Nenufar_amarillo.jpg').
unirPlantaImagen('Artemisa','C:/Proyecto/yerberito/Artemisa.jpg').
unirPlantaImagen('Semilla_de_yute','C:/Proyecto/yerberito/Semilla_de_yute.jpg').
unirPlantaImagen('Toloache','C:/Proyecto/yerberito/Toloache.jpg').
unirPlantaImagen('Eucalipto','C:/Proyecto/yerberito/Eucalipto.jpg').
unirPlantaImagen('Rosal','C:/Proyecto/yerberito/Rosal.jpg').


%SeObtienDeCadaPlanta
planta_obtiene('Digital', 'tonico_cardiaco').
planta_obtiene('Opio', 'morfina').
planta_obtiene('Ipeca', 'emetina').
planta_obtiene('Nuez_vomica', 'estrienica').
planta_obtiene('Eleboro_blanco', 'veratrina').
planta_obtiene('Colchico', 'colquicina').
planta_obtiene('Belladona', 'atropina').
planta_obtiene('Quina', 'quina').
planta_obtiene('Cacao', 'teobromina').
planta_obtiene('Retama', 'esparteina').
planta_obtiene('Coca', 'cocaina').
planta_obtiene('Peyote', 'mescalina').
planta_obtiene('Efedra', 'efedrina').
planta_obtiene('Barrasco', 'hormonas').
planta_obtiene('Nenufar_amarillo', 'lutenurina').
planta_obtiene('Artemisa', 'tauremisina').
planta_obtiene('Semilla_de_yute', 'olitorisida').
planta_obtiene('Toloache', 'acido_lisergico').
planta_obtiene('Eucalipto', 'eucaliptol').
planta_obtiene('Rosal', 'vitamina_c').

%AccionesEfectosDeMedicamentosProvenientesDePlantas
usado_para_tratar('Malva','abscesos').
usado_para_tratar('Zarzaparrilla','absceso_hepatico').
usado_para_tratar('Anis','acidez_estomacal').
usado_para_tratar('Perejil','acidez_estomacal').
usado_para_tratar('Sanguinaria','acido_urico').
usado_para_tratar('Limon','acido_urico').
usado_para_tratar('Sauco','acido_urico').
usado_para_tratar('Árnica','acne').
usado_para_tratar('Llanten','aftas').
usado_para_tratar('Fenogreco','aftas').
usado_para_tratar('Zarzamora','aftas').
usado_para_tratar('Salvia','agotamiento').
usado_para_tratar('Tilo','agotamiento').
usado_para_tratar('Valeriana','agotamiento').
usado_para_tratar('Yerbabuena','agruras').
usado_para_tratar('Manzanilla','agruras').
usado_para_tratar('Jugo_de_limon','agruras').
usado_para_tratar('Jugo_de_toronja','agruras').
usado_para_tratar('Pingüica','albuminaria').
usado_para_tratar('Quinoa_roja','albuminaria').
usado_para_tratar('Encino_rojo','albuminaria').
usado_para_tratar('Pimiento','alcoholismo').
usado_para_tratar('Salvia','almorranas').
usado_para_tratar('Huramelis','almorranas').
usado_para_tratar('Sanguinaria','almorranas').
usado_para_tratar('Cola_de_caballo','almorranas').
usado_para_tratar('Arnica','almorranas').
usado_para_tratar('Sauco','almorranas').
usado_para_tratar('Ajenjo','anemia').
usado_para_tratar('Germen_de_trigo','anemia').
usado_para_tratar('Quira','anemia').
usado_para_tratar('Canela','anemia').
usado_para_tratar('Alholva','anemia').
usado_para_tratar('Eucalipto','anginas').
usado_para_tratar('Cebada','anginas').
usado_para_tratar('Salvia','anginas').
usado_para_tratar('Tabachin','anginas').
usado_para_tratar('Borraja','anginas').
usado_para_tratar('Ajenjo','anorexia').
usado_para_tratar('Gerciana','anorexia').
usado_para_tratar('Yerbabuena','anorexia').
usado_para_tratar('Limon','arterosclerosis').
usado_para_tratar('Genciana','arterosclerosis').
usado_para_tratar('Cardo','arterosclerosis').
usado_para_tratar('Zarzaparrilla','arterosclerosis').
usado_para_tratar('Arnica','arterosclerosis').
usado_para_tratar('Chicalote','arterosclerosis').
usado_para_tratar('Alcanfor','arterosclerosis').
usado_para_tratar('Toronja','arterosclerosis').
usado_para_tratar('Limon','artritis').
usado_para_tratar('Genciana','artritis').
usado_para_tratar('Cardo','artritis').
usado_para_tratar('Zarzaparrilla','artritis').
usado_para_tratar('Arnica','artritis').
usado_para_tratar('Chicalote','artritis').
usado_para_tratar('Alcanfor','artritis').
usado_para_tratar('Toronja','artritis').
usado_para_tratar('Eucalipto','asma').
usado_para_tratar('Merrubio','asma').
usado_para_tratar('Toloache','asma').
usado_para_tratar('Oregano','asma').
usado_para_tratar('Salvia','asma').
usado_para_tratar('Gordolobo','asma').
usado_para_tratar('Lupulo','atonia_estomacal').
usado_para_tratar('Eucalipto','atonia_estomacal').
usado_para_tratar('Cuasia','atonia_estomacal').
usado_para_tratar('Uva','bazo').
usado_para_tratar('Cerezo','bazo').
usado_para_tratar('Malva','inflamacion_de_la_boca').
usado_para_tratar('Rosal','inflamacion_de_la_boca').
usado_para_tratar('Limon','inflamacion_de_la_boca').
usado_para_tratar('Salvia','inflamacion_de_la_boca').
usado_para_tratar('Rosal','estomatitis').
usado_para_tratar('Encina','estomatitis').
usado_para_tratar('Salvia','estomatitis').
usado_para_tratar('Zarzamora','estomatitis').
usado_para_tratar('Eucalipto','bronquitis').
usado_para_tratar('Borraga','bronquitis').
usado_para_tratar('Anacahuite','bronquitis').
usado_para_tratar('Gordolobo','bronquitis').
usado_para_tratar('Tilo','bronquitis').
usado_para_tratar('Benjui','bronquitis').
usado_para_tratar('Marrubio','bronquitis').
usado_para_tratar('Rabano','bronquitis').
usado_para_tratar('Gordolobo','bronconeumonia').
usado_para_tratar('Eucalipto','bronconeumonia').
usado_para_tratar('Ipecacuana','bronconeumonia').
usado_para_tratar('Mostaza','bronconeumonia').
usado_para_tratar('Ortiga','caida_del_cabello').
usado_para_tratar('Espinosilla','caida_del_cabello').
usado_para_tratar('Marrubio','caida_del_cabello').
usado_para_tratar('Romero','caida_del_cabello').
usado_para_tratar('Anis','calambres').
usado_para_tratar('Tila','calambres').
usado_para_tratar('Manzanilla','calambres').
usado_para_tratar('Ajenjo','calambres').
usado_para_tratar('Diente_de_leon','calculos_biliares').
usado_para_tratar('Aceite_de_oliva','calculos_biliares').
usado_para_tratar('Retama','calculos_biliares').
usado_para_tratar('Cabellos_de_elote','calculos_renales').
usado_para_tratar('Pinguica','calculos_renales').
usado_para_tratar('Cola_de_caballo','calculos_renales').
usado_para_tratar('Ajo','callos').
usado_para_tratar('Cebolla','callos').
usado_para_tratar('Hiedra','caries').
usado_para_tratar('Cola_de_caballo','caries').
usado_para_tratar('Ortiga','caspa').
usado_para_tratar('Limon','caspa').
usado_para_tratar('Romero','caspa').
usado_para_tratar('Cuachalalate','cancer_de_utero').
usado_para_tratar('Llanten','cancer_de_utero').
usado_para_tratar('Siempreviva','cancer_de_utero').
usado_para_tratar('Mastuerzo','ciatica').
usado_para_tratar('Higuera','ciatica').
usado_para_tratar('Sauco','ciatica').
usado_para_tratar('Toronjil','circulacion').
usado_para_tratar('Sanguinaria','circulacion').
usado_para_tratar('Salvia','circulacion').
usado_para_tratar('Hamamelis','circulacion').
usado_para_tratar('Cola_de_caballo','cistitis').
usado_para_tratar('Doradilla','cistitis').
usado_para_tratar('Ajo','cistitis').
usado_para_tratar('Cabellos_de_elote','cistitis').
usado_para_tratar('Menta','colicos').
usado_para_tratar('Hinojo','colicos').
usado_para_tratar('Manzanilla','colicos').
usado_para_tratar('Toronjil','colicos').
usado_para_tratar('Boldo','colicos').
usado_para_tratar('Linaza','colitis').
usado_para_tratar('Anis','colitis').
usado_para_tratar('Romero','colitis').
usado_para_tratar('Cola_de_caballo','colitis').
usado_para_tratar('Árnica','contusiones').
usado_para_tratar('Hamamelis','contusiones').
usado_para_tratar('Laurel','contusiones').
usado_para_tratar('Briania','contusiones').
usado_para_tratar('Digital','corazon').
usado_para_tratar('Salvia','corazon').
usado_para_tratar('Nuez_de_kcla','corazon').
usado_para_tratar('Tejocote','corazon').
usado_para_tratar('Achicoria','depurativos_de_la_sangre').
usado_para_tratar('Diente_de_leon','depurativos_de_la_sangre').
usado_para_tratar('Apio','depurativos_de_la_sangre').
usado_para_tratar('Sanguinaria','depurativos_de_la_sangre').
usado_para_tratar('Zarzaparrilla','depurativos_de_la_sangre').
usado_para_tratar('Berro','depurativos_de_la_sangre').
usado_para_tratar('Matarique','diabetes').
usado_para_tratar('Tronadora','diabetes').
usado_para_tratar('Bucalipto','diabetes').
usado_para_tratar('Damiana','diabetes').
usado_para_tratar('Capulin','diarrea_cronica').
usado_para_tratar('Mezquite','diarrea_cronica').
usado_para_tratar('Tlalchichinole','diarrea_cronica').
usado_para_tratar('Linaza','diarrea_por_irritacion').
usado_para_tratar('Membrillo','diarrea_por_irritacion').
usado_para_tratar('Arroz','diarrea_por_irritacion').
usado_para_tratar('Cebada','diarrea_por_irritacion').
usado_para_tratar('Guayaba','diarrea_por_inflamacion').
usado_para_tratar('Albahaca','diarrea_por_inflamacion').
usado_para_tratar('Granada','diarrea_por_inflamacion').
usado_para_tratar('Manzanilla','diarrea_verdosa').
usado_para_tratar('Sinionillo','diarrea_verdosa').
usado_para_tratar('Siempreviva','diarrea_verdosa').
usado_para_tratar('Chaparro_amargoso','diarrea_con_sangre').
usado_para_tratar('Muicle','diarrea_con_sangre').
usado_para_tratar('Monacillo','diarrea_con_sangre').
usado_para_tratar('Limon','difteria').
usado_para_tratar('Naranja','difteria').
usado_para_tratar('Tamarindo','disenteria').
usado_para_tratar('Chaparro_amargoso','disenteria').
usado_para_tratar('Ipecacuana','disenteria').
usado_para_tratar('Cedron','disenteria').
usado_para_tratar('Anis','dispepsia').
usado_para_tratar('Menta','dispepsia').
usado_para_tratar('Yerbabuena','dispepsia').
usado_para_tratar('Diente_de_leon','dispepsia').
usado_para_tratar('Te_de_limon','dispepsia').
usado_para_tratar('Quina','dispepsia').
usado_para_tratar('Genciana','dispepsia').
usado_para_tratar('Tabequillo','dispepsia').
usado_para_tratar('Ruibaxbo','dispepsia').
usado_para_tratar('Anis_estrella','dolor').
usado_para_tratar('Valeriana','dolor').
usado_para_tratar('Manzanilla','dolor').
usado_para_tratar('Alcanfor','dolores_musculares').
usado_para_tratar('Tamarindo','empacho').
usado_para_tratar('Linaza','enteritis').
usado_para_tratar('Cedron','enteritis').
usado_para_tratar('Llanten','enteritis').
usado_para_tratar('Valeriana','epilepsia').
usado_para_tratar('Hierba_del_pollo','epistaxis').
usado_para_tratar('Cebolla','epistaxis').
usado_para_tratar('Perejil','epistaxis').
usado_para_tratar('Sauco','erisipela').
usado_para_tratar('Hiedra','erisipela').
usado_para_tratar('Zanahoria','erisipela').
usado_para_tratar('Borraja','escarlatina').
usado_para_tratar('Sauco','escarlatina').
usado_para_tratar('Cebolla','escarlatina').
usado_para_tratar('Ajo','escorbuto').
usado_para_tratar('Limon','escorbuto').
usado_para_tratar('Berro','escorbuto').
usado_para_tratar('Cebolla','escorbuto').
usado_para_tratar('Geranio','escorbuto').
usado_para_tratar('Ciruela','estreñimiento').
usado_para_tratar('Linaza','estreñimiento').
usado_para_tratar('Chia','estreñimiento').
usado_para_tratar('Tamarindo','estreñimiento').
usado_para_tratar('Agar_agar','estreñimiento').
usado_para_tratar('Eucalipto','faringitis').
usado_para_tratar('Lavanda','faringitis').
usado_para_tratar('Anacahuite','faringitis').
usado_para_tratar('Apio','flatulencia').
usado_para_tratar('Tomillo','flatulencia').
usado_para_tratar('Perejil','flatulencia').
usado_para_tratar('Anis','flatulencia').
usado_para_tratar('Hinojo','flatulencia').
usado_para_tratar('Toronjil','flatulencia').
usado_para_tratar('Romero','flatulencia').
usado_para_tratar('Ruibarbo','flatulencia').
usado_para_tratar('Ruda','flatulencia').
usado_para_tratar('Menta','flatulencia').
usado_para_tratar('Ármica','flebitis').
usado_para_tratar('Alfalfa_','flebitis').
usado_para_tratar('Lino','flebitis').
usado_para_tratar('Malvavisco','flebitis').
usado_para_tratar('Romero','flebitis').
usado_para_tratar('Quina','flebitis').
usado_para_tratar('Genciana_','flemas').
usado_para_tratar('Oregano','flemas').
usado_para_tratar('Fenogreco','forunculos').
usado_para_tratar('Malvavisco','forunculos').
usado_para_tratar('Hiedra','forunculos').
usado_para_tratar('Manzanilla','gastralgia').
usado_para_tratar('Anis_de_estrella','gastralgia').
usado_para_tratar('Cola_de_caballo','gonorrea').
usado_para_tratar('Doradilla','gonorrea').
usado_para_tratar('Zarzaparrilla','gonorrea').
usado_para_tratar('Apio','gota').
usado_para_tratar('Cerezo','gota').
usado_para_tratar('Limon','gota').
usado_para_tratar('Pino','gota').
usado_para_tratar('Alcanfor','gota').
usado_para_tratar('Aconito','gota').
usado_para_tratar('Belladona','gota').
usado_para_tratar('Beleño','gota').
usado_para_tratar('Colchico','gota').
usado_para_tratar('Chicalote','gota').
usado_para_tratar('Encina','grietas_del_ano').
usado_para_tratar('Encina','grietas_del_pezon').
usado_para_tratar('Nogal','grietas_del_pezon').
usado_para_tratar('Milenrana','grietas_del_pezon').
usado_para_tratar('Eucalipto','gripe').
usado_para_tratar('Limon','gripe').
usado_para_tratar('Quina','gripe').
usado_para_tratar('Zarzaparrilla','gripe').
usado_para_tratar('Calendula','gripe').
usado_para_tratar('Hinojo','halitosis').
usado_para_tratar('Menta','halitosis').
usado_para_tratar('Mastuerzo','hemorraga_interna').
usado_para_tratar('Ortiga','hemorraga_interna').
usado_para_tratar('Rosal','hemorraga_interna').
usado_para_tratar('Retama','hepatitis').
usado_para_tratar('Boldo','hepatitis').
usado_para_tratar('Alcachofa','hepatitis').
usado_para_tratar('Prodigiosa','hepatitis').
usado_para_tratar('Cascara_sagrada','hepatitis').
usado_para_tratar('Helecho','hernia').
usado_para_tratar('Ricino','hernia').
usado_para_tratar('Tabaco','hernia').
usado_para_tratar('Linaza','herpes').
usado_para_tratar('Llanten','herpes').
usado_para_tratar('Árnica_','heridas').
usado_para_tratar('Hamamelis','heridas').
usado_para_tratar('Alcachofa','hidropesia').
usado_para_tratar('Cardo','hidropesia').
usado_para_tratar('Perejil','hidropesia').
usado_para_tratar('Sauco','hidropesia').
usado_para_tratar('Berros','hidropesia').
usado_para_tratar('Retama','hidropesia').
usado_para_tratar('Marrubio','congestion_en_el_higado').
usado_para_tratar('Boldo','congestion_en_el_higado').
usado_para_tratar('Doradilla','congestion_en_el_higado').
usado_para_tratar('Ruibarbo','congestion_en_el_higado').
usado_para_tratar('Manzanilla','colico').
usado_para_tratar('Lechuga','bilis').
usado_para_tratar('Tila','bilis').
usado_para_tratar('Papoloquelite','letericia').
usado_para_tratar('Achicoria','letericia').
usado_para_tratar('Berros','letericia').
usado_para_tratar('Llanten','letericia').
usado_para_tratar('Retama','letericia').
usado_para_tratar('Tecomasuchil','letericia').
usado_para_tratar('Ajo','hipertension').
usado_para_tratar('Esparrago','hipertension').
usado_para_tratar('Alpiste','hipertension').
usado_para_tratar('Muerdago','hipertension').
usado_para_tratar('Miel','hipotension').
usado_para_tratar('Nuez_de_kola','hipotension').
usado_para_tratar('Crategus','hipotension').
usado_para_tratar('Acedera','hipotension').
usado_para_tratar('Anis','hipo').
usado_para_tratar('Hinojo','hipo').
usado_para_tratar('Tila','hipo').
usado_para_tratar('Valeriana','hipo').
usado_para_tratar('Azahar','histerismo').
usado_para_tratar('Beleño','histerismo').
usado_para_tratar('Gelsenio','histerismo').
usado_para_tratar('Tila','histerismo').
usado_para_tratar('Valeriana','histerismo').
usado_para_tratar('Pastiflora','insomio').
usado_para_tratar('Azahar','insomio').
usado_para_tratar('Menta','insomio').
usado_para_tratar('Manzanilla','insomio').
usado_para_tratar('Lechuga','insomio').
usado_para_tratar('Genciana_','intestino').
usado_para_tratar('Melisa','intestino').
usado_para_tratar('Yohimbo','impotencia_sexual').
usado_para_tratar('Damiana','impotencia_sexual').
usado_para_tratar('Nuex_vomica','impotencia_sexual').
usado_para_tratar('Aguacate','impotencia_sexual').
usado_para_tratar('Manzanilla','jaqueca').
usado_para_tratar('Aconito','jaqueca').
usado_para_tratar('Valeriana','jaqueca').
usado_para_tratar('Tila','jaqueca').
usado_para_tratar('Chicalote','jaqueca').
usado_para_tratar('Hinojo','lactancia').
usado_para_tratar('Anis','lactancia').
usado_para_tratar('Menta','lactancia').
usado_para_tratar('Perejil','lactancia').
usado_para_tratar('Zanahoria','lactancia').
usado_para_tratar('Aconito','laringitis').
usado_para_tratar('Borraja','laringitis').
usado_para_tratar('Cebolla','laringitis').
usado_para_tratar('Rosal','laringitis').
usado_para_tratar('Benjui','laringitis').
usado_para_tratar('Encina','laringitis').
usado_para_tratar('Encina','leucorrea').
usado_para_tratar('Zarzaparrilla','leucorrea').
usado_para_tratar('Pino','leucorrea').
usado_para_tratar('Enebro','leucorrea').
usado_para_tratar('Genciana_','leucorrea').
usado_para_tratar('Ajenjo','lombrices').
usado_para_tratar('Ajo','lombrices').
usado_para_tratar('Cebolla','lombrices').
usado_para_tratar('Brionia','lombrices').
usado_para_tratar('Aguacate','lombrices').
usado_para_tratar('Papaya','lombrices').
usado_para_tratar('Avena','lumbago').
usado_para_tratar('Cebada','lumbago').
usado_para_tratar('Tomillo','lumbago').
usado_para_tratar('Verbena','lumbago').
usado_para_tratar('Fenogreco','llagas').
usado_para_tratar('Eucalipto','llagas').
usado_para_tratar('Llanten','llagas').
usado_para_tratar('Sanguinaria','llagas').
usado_para_tratar('Quina','malaria').
usado_para_tratar('Girasol','malaria').
usado_para_tratar('Eucalipto','malaria').
usado_para_tratar('Cardo','malaria').
usado_para_tratar('Azahar','menopausia').
usado_para_tratar('Hamamelis','menopausia').
usado_para_tratar('Tila','menopausia').
usado_para_tratar('Quina_roja','menopausia').
usado_para_tratar('Azafran','menstruacion').
usado_para_tratar('Hamamelis','menstruacion').
usado_para_tratar('Belladona','menstruacion').
usado_para_tratar('Anis_de_estrella','menstruacion').
usado_para_tratar('Ruda','menstruacion').
usado_para_tratar('Ajenjo','menstruacion').
usado_para_tratar('Manzanilla','menstruacion').
usado_para_tratar('Apio','menstruacion').
usado_para_tratar('Hisopol','menstruacion').
usado_para_tratar('Quina_amarilla','menstruacion').
usado_para_tratar('Sabina','menstruacion').
usado_para_tratar('Artemisa','menstruacion').
usado_para_tratar('Hamamelis','metorragia').
usado_para_tratar('Zoapatle','metorragia').
usado_para_tratar('Perejil','metorragia').
usado_para_tratar('Cuercillo','metorragia').
usado_para_tratar('Clavo','muelas').
usado_para_tratar('Heidra','muelas').
usado_para_tratar('Ortiga','nariz').
usado_para_tratar('Cola_de_caballo','nariz').
usado_para_tratar('Ruda','nariz').
usado_para_tratar('Eucalipto','nariz').
usado_para_tratar('Anis','nauseas').
usado_para_tratar('Ajenjo','nauseas').
usado_para_tratar('Menta','nauseas').
usado_para_tratar('Salvia','nauseas').
usado_para_tratar('Manzanilla','neuralgias').
usado_para_tratar('Menta','neuralgias').
usado_para_tratar('Valeriana','neuralgias').
usado_para_tratar('Bolde','neuralgias').
usado_para_tratar('Rasiflora','neurastenia').
usado_para_tratar('Te_negro','neurastenia').
usado_para_tratar('Mate','neurastenia').
usado_para_tratar('Valeriana','neurastenia').
usado_para_tratar('Linaza','nefritis').
usado_para_tratar('Grama','nefritis').
usado_para_tratar('Cebada','nefritis').
usado_para_tratar('Llanten','nefritis').
usado_para_tratar('Doradilla','nefritis').
usado_para_tratar('Esparrago_ruda','nefritis').
usado_para_tratar('Toronjil','obesidad').
usado_para_tratar('Marrubio','obesidad').
usado_para_tratar('Limon','obesidad').
usado_para_tratar('Malva','obesidad').
usado_para_tratar('Esparrago','obesidad').
usado_para_tratar('Boldo','oidos').
usado_para_tratar('Aceite_de_oliva','oidos').
usado_para_tratar('Llanten','oidos').
usado_para_tratar('Hiedra','oidos').
usado_para_tratar('Manzanilla','conjuntivitis').
usado_para_tratar('Limon','conjuntivitis').
usado_para_tratar('Llanten','conjuntivitis').
usado_para_tratar('Salvia','conjuntivitis').
usado_para_tratar('Ruda','conjuntivitis').
usado_para_tratar('Rosal','conjuntivitis').
usado_para_tratar('Ajenjo','paludismo').
usado_para_tratar('Quina','paludismo').
usado_para_tratar('Berros','pecas').
usado_para_tratar('Genciana_','pecas').
usado_para_tratar('Rabano','pecas').
usado_para_tratar('Papaija','pecas').
usado_para_tratar('Laurel','pies olorosos').
usado_para_tratar('Encina','pies_olorosos').
usado_para_tratar('Miel','piquetes').
usado_para_tratar('Perejil','piquetes').
usado_para_tratar('Cebolla','piquetes').
usado_para_tratar('Puerro','piquetes').
usado_para_tratar('Fresno','piquetes').
usado_para_tratar('Ipecacuana','piquetes').
usado_para_tratar('Alcanfor','piquetes').
usado_para_tratar('Hamamelis','piquetes').
usado_para_tratar('Anagalida','piquetes').
usado_para_tratar('Jengibre','pleuresia').
usado_para_tratar('Linaza','pleuresia').
usado_para_tratar('Cardo','pleuresia').
usado_para_tratar('Girasol','pleuresia').
usado_para_tratar('Ipecacuana','piorrea').
usado_para_tratar('Cola_de_caballo','prostata').
usado_para_tratar('Eucalipto','pulmonia').
usado_para_tratar('Ocote','pulmonia').
usado_para_tratar('Gordolobo','pulmonia').
usado_para_tratar('Borraja','pulmonia').
usado_para_tratar('Sauco','pulmonia').
usado_para_tratar('Linaza','quemaduras').
usado_para_tratar('Cebolla','quemaduras').
usado_para_tratar('Hiedra','quemaduras').
usado_para_tratar('Gordolobo','quemaduras').
usado_para_tratar('Nogal','raquitismo').
usado_para_tratar('Ajo','reumatismo').
usado_para_tratar('Apio','reumatismo').
usado_para_tratar('Borraja','reumatismo').
usado_para_tratar('Gobernadora','reumatismo').
usado_para_tratar('Pino','reumatismo').
usado_para_tratar('Romero','reumatismo').
usado_para_tratar('Sanguinaria','reumatismo').
usado_para_tratar('Marrubio','reumatismo').
usado_para_tratar('Tabaco','reumatismo').
usado_para_tratar('Cabellos_de_elote','riñones').
usado_para_tratar('Cola_de_caballo','riñones').
usado_para_tratar('Apio','riñones').
usado_para_tratar('Eucalipto','ronquera').
usado_para_tratar('Pino','ronquera').
usado_para_tratar('Gordolobo','ronquera').
usado_para_tratar('Ajo','ronquera').
usado_para_tratar('Cebolla','ronquera').
usado_para_tratar('Estafiate','san_vito').
usado_para_tratar('Valeriana','san_vito').
usado_para_tratar('Borraja','sarampion').
usado_para_tratar('Ortiga','sarampion').
usado_para_tratar('Sauco','sarampion').
usado_para_tratar('Ajo','sarna').
usado_para_tratar('Alcanfor','sarna').
usado_para_tratar('Menta','sarna').
usado_para_tratar('Tomillo','sarna').
usado_para_tratar('Romero','sarna').
usado_para_tratar('Encina','sarpullido').
usado_para_tratar('Salvia','sarpullido').
usado_para_tratar('Tila','sarpullido').
usado_para_tratar('Limon','sed').
usado_para_tratar('Tamarindo','sed').
usado_para_tratar('Pirul','sed').
usado_para_tratar('Semilla_de_calabaza','solitaria').
usado_para_tratar('Coquito_de_aceite','solitaria').
usado_para_tratar('Helecho_macho','solitaria').
usado_para_tratar('Encina','sudoracion_escesiva').
usado_para_tratar('Alcanfor','tifoidea').
usado_para_tratar('Borraja','tifoidea').
usado_para_tratar('Quina_','tifoidea').
usado_para_tratar('Canela','tifoidea').
usado_para_tratar('Romero','tifoidea').
usado_para_tratar('Salvia','tifoidea').
usado_para_tratar('Berro_','tiña').
usado_para_tratar('Tamarindo','tiña').
usado_para_tratar('Salvia','tiña').
usado_para_tratar('Eucalipto','tos').
usado_para_tratar('Capulin','tos').
usado_para_tratar('Cedron','tos').
usado_para_tratar('Salvia','tos').
usado_para_tratar('Malva','tos').
usado_para_tratar('Marrubio','tos').
usado_para_tratar('Gordolobo','tos').
usado_para_tratar('Gelsemio','tos_ferina').
usado_para_tratar('Quina','tos_ferina').
usado_para_tratar('Rabano','tos_ferina').
usado_para_tratar('Violeta','tos_ferina').
usado_para_tratar('Jugo_de_vastago_de_platano_morado','tuberculosis').
usado_para_tratar('Mastuerzo','tuberculosis').
usado_para_tratar('Berro','tuberculosis').
usado_para_tratar('Ajo','tuberculosis').
usado_para_tratar('Eucalipto','tuberculosis').
usado_para_tratar('Pirul','tuberculosis').
usado_para_tratar('Pino','tuberculosis').
usado_para_tratar('Roble','tuberculosis').
usado_para_tratar('Cuachalalate','ulcera').
usado_para_tratar('Sanguinaria','ulcera').
usado_para_tratar('Cola_de_caballo','ulcera').
usado_para_tratar('Girasol','ulcera').
usado_para_tratar('Limon','urticaria').
usado_para_tratar('Ruibarbo','urticaria').
usado_para_tratar('Hamamelis','varices').
usado_para_tratar('Castaño_de_indias','varices').
usado_para_tratar('Llanten','varices').
usado_para_tratar('Toronjil','varices').
usado_para_tratar('Gordolobo','varices').
usado_para_tratar('Apio','vejiga').
usado_para_tratar('Cipres','vejiga').
usado_para_tratar('Cola_de_caballo','vejiga').
usado_para_tratar('Ortiga','vejiga').
usado_para_tratar('Malva','vejiga').
usado_para_tratar('Leche_de_higuera','verrugas').
usado_para_tratar('Cebolla','verrugas').
usado_para_tratar('Nogal','verrugas').
usado_para_tratar('Albahaca','vertigos').
usado_para_tratar('Espino','vertigos').
usado_para_tratar('Menta','vomitos').
usado_para_tratar('Tila','vomitos').
usado_para_tratar('Marrubio','vomitos').
usado_para_tratar('Valeriana','vomitos').
usado_para_tratar('Salvia','vomitos').
usado_para_tratar('Cilantro','voz').
usado_para_tratar('Ajo','voz').
usado_para_tratar('Limon','voz').
usado_para_tratar('Pino','voz').
usado_para_tratar('Alfalfa','vitaminas').
usado_para_tratar('Espinacas','vitaminas').
usado_para_tratar('Acelga','vitaminas').
usado_para_tratar('Berro','vitaminas').
usado_para_tratar('Cebolla','vitaminas').
usado_para_tratar('Limon','vitaminas').
usado_para_tratar('Zanahoria','vitaminas').
usado_para_tratar('Abrojo','afecciones_del_pecho').
usado_para_tratar('Abrojo','inflamacion_de_los_ojos').
usado_para_tratar('Abrojo','inflamacion_del_higado').
usado_para_tratar('Abrojo','favorece_circulacion_de_la_sangre').
usado_para_tratar('Acacia',' garganta_estropeada').
usado_para_tratar('Acacia',' quemaduras').
usado_para_tratar('Acacia',' bronquitis').
usado_para_tratar('Acacia',' tos').
usado_para_tratar('Acacia',' dolor_de_garganta').
usado_para_tratar('Acanto',' picadura_de_araña').
usado_para_tratar('Acanto',' desinflamar').
usado_para_tratar('Acanto',' sacar_veneno').
usado_para_tratar('Acanto',' almorranas').
usado_para_tratar('Acanto',' ardores_de_orina').
usado_para_tratar('Acanto',' heridas_por_golpe_o_caida').
usado_para_tratar('Acanto',' dispepsia').
usado_para_tratar('Acanto',' disenteria').
usado_para_tratar('Aceitilla','cansancio_intelectual').
usado_para_tratar('Aceitilla','depresion_nerviosa').
usado_para_tratar('Aceitilla','mujer_histerica').
usado_para_tratar('Aceitilla','mujer_con_muchos_nervios').
usado_para_tratar('Aceitilla','tonicidad_nerviosa').
usado_para_tratar('Aceitilla','tonicidad_cerebral').
usado_para_tratar('Achicoria','diuretico').
usado_para_tratar('Achicoria','depurativo').
usado_para_tratar('Achicoria','dificil_digestion').
usado_para_tratar('Achicoria','colicos_biliosos').
usado_para_tratar('Achicoria','estreñimiento').
usado_para_tratar('Gordolobo','hemorroides').
usado_para_tratar('Grama','curar_golpes_internos').
usado_para_tratar('Grama','infeccion_en_los_riñones').
usado_para_tratar('Grama','mal_de_orin').
usado_para_tratar('Grama','inflamaciones_en_general').
usado_para_tratar('Granado','lombrices').

%SignificadosDeEfectosDeLasPlantas
significa('Afrodisiaca','exita el apetito sexual').
significa('Analgesica','quita_o_modera_el_dolor').
significa('Anestesica','insensibiliza_el_cuerpo').
significa('Antidiarreica','controla_diarreas').
significa('Antiespasmodica','controla_espasmos_nerviosos').
significa('Antiflogistica','ayuda_con_inflamaciones').
significa('Antipiretica','quita_la_fiebre').
significa('Antiseptica','mata_los_tejidos').
significa('Aperitiva','deseo_de_comer').
significa('Astringente','contrae_los_tejidos').
significa('Carminativa','evita_formacion_de_gases').
significa('Colagoga','ayuda_a_expulsar_la_bilis').
significa('Depurativa','limpia_y_purifica_la_sangre').
significa('Diaforetica','provoca_sudoracion_como_cochino').
significa('Digestiva','favorece_a_la_digestion').
significa('Diuretica','provoca_la_orina').
significa('Emetica','provoca_nauseas_y_vomitos').
significa('Emenagoga','activa_la_menstruacion').
significa('Estupefaciente','ayuda_a_tranquilizar').
significa('Hemostatica','detiene_las_hemorragias').
significa('Hepatica','ayuda_al_higado').
significa('Laxante','purga_sin_provocar_diarrea').
significa('Pectoral','ayuda_al_pecho').
significa('Sedante','calma_dolores_intestinales').
significa('Tonica','fortalece_el_organismo').
significa('Toxica','es_venenosa').
significa('Vermifuga','expulsa_gusanos_intestinales').
significa('Vulneraria','cura_llagas_y_heridas').
